# Generated by Django 6.0.5 on 2026-05-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='commodity',
        ),
        migrations.AddField(
            model_name='commodity',
            name='unit',
            field=models.CharField(default='tonnes', max_length=255),
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('production', models.FloatField()),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.commodity')),
            ],
        ),
    ]
