# Generated by Django 6.0.5 on 2026-05-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_asset_commodity_commodity_unit_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_endpoint_ReCiPe2016_ecosystem_diversity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_endpoint_ReCiPe2016_human_health',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_endpoint_ReCiPe2016_resource_availability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_climate_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_freshwater_ecotoxicity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_freshwater_eutrophication',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_marine_eutrophication',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_ozonedepletion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_resource_depletion_fossil',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_resource_depletion_minerals',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_soil_acidification',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_terrestrial_acidification',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_water_consumption',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Company_Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy_type')),
            ],
        ),
    ]
