# Generated by Django 6.0.5 on 2026-05-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_policy_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='company_policy',
            name='policy_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='company_policy',
            name='policy_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy_level'),
        ),
        migrations.AlterUniqueTogether(
            name='company_policy',
            unique_together={('company', 'policy_level')},
        ),
        migrations.CreateModel(
            name='Policy_Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy_type')),
            ],
        ),
        migrations.AddField(
            model_name='policy_level',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy_subcategory'),
        ),
        migrations.RemoveField(
            model_name='company_policy',
            name='policy_type',
        ),
    ]
