# Generated by Django 6.0.5 on 2026-05-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_policy_level_company_policy_policy_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('NACE_code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('NACE_code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Water_dependency', models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2)),
                ('Pollination_dependency', models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2)),
                ('Soil_quality_dependency', models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2)),
                ('Carbon_Sequestration', models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2)),
                ('Water_purification_dependency', models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2)),
                ('Pest_control_dependency', models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Revenue_Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subsector')),
            ],
        ),
    ]
