# Generated by Django 6.0.5 on 2026-05-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sector_subsector_company_revenue_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='Asset',
        ),
        migrations.AddField(
            model_name='commodity',
            name='dependency_carbon_sequestration',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2),
        ),
        migrations.AddField(
            model_name='commodity',
            name='dependency_pest_control',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2),
        ),
        migrations.AddField(
            model_name='commodity',
            name='dependency_pollination',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2),
        ),
        migrations.AddField(
            model_name='commodity',
            name='dependency_soil_quality',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2),
        ),
        migrations.AddField(
            model_name='commodity',
            name='dependency_water',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2),
        ),
        migrations.AddField(
            model_name='commodity',
            name='dependency_water_purification',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', max_length=2),
        ),
        migrations.AddField(
            model_name='production',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='production',
            name='scope',
            field=models.CharField(choices=[('direct production', 'Direct production'), ('Tier 1 upstream', 'Tier 1 upstream'), ('Tier 2 upstream', 'Tier 2 upstream'), ('Raw material', 'Raw material')], default='direct production', max_length=50),
        ),
        migrations.AddField(
            model_name='production',
            name='subnational_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subnationalregion'),
        ),
        migrations.AddField(
            model_name='production',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset'),
        ),
    ]
