# Generated by Django 6.0.5 on 2026-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_production_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='scope',
            field=models.CharField(choices=[('direct production', 'Direct production'), ('Tier 1 upstream', 'Tier 1 upstream'), ('Tier 2 upstream', 'Tier 2 upstream'), ('Raw material', 'Raw material')], default='direct production'),
        ),
    ]
