# Generated by Django 6.0.5 on 2026-05-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_production_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='scope',
        ),
        migrations.AddField(
            model_name='production',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
        ),
    ]
