# Generated by Django 6.0.5 on 2026-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_production_scope_production_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='scope',
            field=models.CharField(choices=[('direct', 'direct'), ('tier 1', 'tier 1'), ('tier 2', 'tier 2'), ('raw material', 'raw material')], default='direct', max_length=15),
        ),
    ]
