# Generated by Django 6.0.5 on 2026-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_production_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='risk_carbon_sequestration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_coastal_inundation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_cyclone',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_drought',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_flood',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_heatwave',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_pest_control',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_pollination',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_precipitation_variation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_soil_quality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_temperature_variation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_water',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_water_purification',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_water_stress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_wildfire',
            field=models.FloatField(default=0),
        ),
    ]
