# Generated by Django 6.0.5 on 2026-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_asset_risk_carbon_sequestration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='estimated_revenue',
            field=models.FloatField(default=0.0),
        ),
    ]
