# Generated by Django 6.0.5 on 2026-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_production_estimated_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_coastal_inundation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_cyclone',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_drought',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_flood',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_heatwave',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_precipitation_variation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_temperature_variation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_water_stress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulenrability_wildfire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulnerability_carbon_sequestration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulnerability_pest_control',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulnerability_pollination',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulnerability_soil_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulnerability_water',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy_level',
            name='vulnerability_water_purification',
            field=models.FloatField(default=0.0),
        ),
    ]
