# Generated by Django 6.0.5 on 2026-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_policy_level_vulenrability_coastal_inundation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='ticker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
