# Generated by Django 6.0.5 on 2026-06-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_company_isin_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='biodiversity_loss_class',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Urbanisation', 'Urbanisation'), ('Mining', 'Mining')], default='Agriculture'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_endpoint_GBS_terrestrial_dynamic',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_endpoint_GBS_terrestrial_static',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_land_use',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='biodiversity_loss_agriculture',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='biodiversity_loss_mining',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='biodiversity_loss_urbanization',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='restoration_cost_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subnationalregion',
            name='restoration_cost_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='isin',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.CreateModel(
            name='Asset_consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_area', models.FloatField(default=0)),
                ('water_consumption', models.FloatField(default=0)),
                ('energy_consumption', models.FloatField(default=0)),
                ('CO2_emissions', models.FloatField(default=0)),
                ('waste_generated', models.FloatField(default=0)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset')),
            ],
        ),
    ]
