# Generated by Django 6.0.5 on 2026-06-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_commodity_biodiversity_loss_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='subnational_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subnationalregion'),
        ),
    ]
