# Generated by Django 6.0.5 on 2026-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_asset_subnational_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnationalregion',
            name='Mean_X',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subnationalregion',
            name='Mean_Y',
            field=models.FloatField(default=0),
        ),
    ]
