# Generated by Django 6.0.5 on 2026-06-11 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_add_subnationalregion_mean_coords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='near_sensitive_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='sensitive_zone_area_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='sensitive_zone_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='sensitive_zone_type',
            field=models.CharField(blank=True, choices=[('NATURA_2000', 'Natura 2000'), ('NATIONAL_PROTECTED', 'Aire protégée nationale'), ('UNESCO', 'Site UNESCO'), ('IUCN_KBA', 'IUCN Key Biodiversity Area'), ('OTHER', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='E4Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.IntegerField(default=2024)),
                ('standard_version', models.CharField(choices=[('AMENDED_2025', 'ESRS E4 amendé (déc. 2025) — 5 DR'), ('ORIGINAL_2023', 'ESRS E4 original (2023) — 6 DR')], default='AMENDED_2025', max_length=20)),
                ('materiality_status', models.CharField(choices=[('NOT_ASSESSED', 'Non évaluée'), ('MATERIAL', 'Matérielle'), ('NOT_MATERIAL', 'Non matérielle')], default='NOT_ASSESSED', max_length=20)),
                ('materiality_justification', models.TextField(blank=True)),
                ('leap_locate_status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Fait')], default='TODO', max_length=20)),
                ('leap_evaluate_status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Fait')], default='TODO', max_length=20)),
                ('leap_assess_status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Fait')], default='TODO', max_length=20)),
                ('leap_locate_notes', models.TextField(blank=True)),
                ('leap_evaluate_notes', models.TextField(blank=True)),
                ('leap_assess_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e4_assessments', to='dashboard.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisclosureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('E4_1', 'E4-1'), ('E4_2', 'E4-2'), ('E4_3', 'E4-3'), ('E4_4', 'E4-4'), ('E4_5', 'E4-5'), ('E4_6', 'E4-6')], max_length=10)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non commencé'), ('NON_COMPLIANT', 'Non conforme'), ('PARTIAL', 'Partiel'), ('COMPLIANT', 'Conforme'), ('NOT_APPLICABLE', 'Non applicable')], default='NOT_STARTED', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_requirements', to='dashboard.e4assessment')),
            ],
            options={
                'unique_together': {('assessment', 'code')},
            },
        ),
    ]
