# Generated by Django 6.0.5 on 2026-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_e4_compliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=3)),
                ('ratio_USD', models.FloatField(default=1)),
            ],
        ),
    ]
