# Generated by Django 6.0.5 on 2026-06-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_policy',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Carbon_emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('scope', models.CharField(max_length=255)),
                ('carbon_emission', models.FloatField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
            options={
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ESG_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('employees_number', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
            options={
                'unique_together': {('company', 'year')},
            },
        ),
    ]
