# Generated by Django 6.0.5 on 2026-06-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_company_policy_comment_carbon_emission_esg_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carbon_emission',
            unique_together={('company', 'year', 'scope')},
        ),
    ]
