# Generated by Django 6.0.5 on 2026-06-20 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_carbon_emission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_productions', to='dashboard.asset'),
        ),
        migrations.AddField(
            model_name='production',
            name='supplier_data_confidence',
            field=models.CharField(choices=[('country level', 'country'), ('sub_region level', 'sub_region'), ('asset level', 'asset')], default='country level', max_length=16),
        ),
        migrations.AlterField(
            model_name='production',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_productions', to='dashboard.asset'),
        ),
    ]
