# Generated by Django 6.0.5 on 2026-06-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_production_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='production',
            name='supplier_data_confidence',
        ),
        migrations.AlterField(
            model_name='production',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset'),
        ),
        migrations.CreateModel(
            name='Supply_chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('year', models.IntegerField()),
                ('supplier_data_confidence', models.CharField(choices=[('country level', 'country'), ('sub_region level', 'sub_region'), ('asset level', 'asset')], default='country level', max_length=16)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_productions', to='dashboard.asset')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.commodity')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_productions', to='dashboard.asset')),
            ],
        ),
    ]
