# Generated by Django 6.0.5 on 2026-07-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_production_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(choices=[('MIDPOINT', 'Midpoint'), ('ENDPOINT', 'Endpoint')], default='MIDPOINT', max_length=10)),
                ('theme', models.CharField(blank=True, max_length=30)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dashboard.impactmethod')),
            ],
        ),
    ]
