# Generated by Django 6.0.5 on 2026-07-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_impact_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterizationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='dashboard.impactcategory')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfs', to='dashboard.commodity')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subnationalregion')),
            ],
            options={
                'unique_together': {('category', 'commodity', 'region', 'country')},
            },
        ),
    ]
