# Generated by Django 6.0.5 on 2026-07-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_backfill_global_cfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='impact_endpoint_GBS_terrestrial_dynamic',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_endpoint_GBS_terrestrial_static',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_endpoint_ReCiPe2016_ecosystem_diversity',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_endpoint_ReCiPe2016_human_health',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_endpoint_ReCiPe2016_resource_availability',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_climate_change',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_freshwater_ecotoxicity',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_freshwater_eutrophication',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_land_use',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_marine_eutrophication',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_ozonedepletion',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_resource_depletion_fossil',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_resource_depletion_minerals',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_soil_acidification',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_terrestrial_acidification',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='impact_midpoint_ReCiPe2016_water_consumption',
        ),
    ]
