# Generated by Django 6.0.5 on 2026-07-05 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_supplynode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('year', models.IntegerField()),
                ('tier', models.PositiveSmallIntegerField(default=0)),
                ('data_confidence', models.CharField(choices=[('asset', 'asset'), ('region', 'region'), ('country', 'country')], default='country', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.commodity')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='dashboard.supplynode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='dashboard.supplynode')),
            ],
        ),
    ]
