# Generated by Django 6.0.5 on 2026-07-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='tier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
