# Generated by Django 6.0.5 on 2026-07-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_migrate_supply_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='scope',
        ),
        migrations.DeleteModel(
            name='Supply_chain',
        ),
    ]
