# Generated by Django 6.0.5 on 2026-07-06 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_drop_scope_and_supply_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='tier',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='production',
            name='tier',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
