# Generated by Django 6.0.5 on 2026-07-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_tier_max_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('theme', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
