# Generated by Django 6.0.5 on 2026-07-06 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_seed_flows'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField(default=0.0)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='dashboard.asset')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.flow')),
            ],
            options={
                'unique_together': {('asset', 'flow', 'year')},
            },
        ),
    ]
