# Generated by Django 6.0.5 on 2026-07-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_migrate_asset_consumption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset_consumption',
        ),
    ]
