# Generated by Django 6.0.5 on 2026-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_drop_asset_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('Airport', 'Airport'), ('Mine', 'Mine'), ('Aluminium', 'Aluminium'), ('Factory', 'Factory'), ('Forest', 'Forest'), ('Office', 'Office'), ('Paper', 'Paper'), ('Refinery', 'Refinery'), ('Renewable', 'Renewable'), ('Smelter', 'Smelter')], default='Factory', max_length=255),
        ),
    ]
