# Generated by Django 6.0.5 on 2026-07-31 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(choices=[('ORDERLY', 'Transition ordonnée'), ('DISORDERLY', 'Transition désordonnée'), ('TOO_LITTLE', 'Trop peu, trop tard'), ('HOT_HOUSE', 'Monde en surchauffe')], default='ORDERLY', max_length=20)),
                ('narrative', models.TextField(blank=True)),
                ('warming_c', models.FloatField(default=0.0)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='SectorCreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_baseline', models.FloatField(default=0.015)),
                ('ebitda_margin', models.FloatField(default=0.12)),
                ('ebitda_volatility', models.FloatField(default=0.25)),
                ('carbon_pass_through', models.FloatField(default=0.3)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to='dashboard.sector')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('key', models.CharField(choices=[('carbon_price', 'Prix du carbone (€/tCO₂e)'), ('hazard_multiplier', "Multiplicateur d'aléa")], max_length=30)),
                ('value', models.FloatField(default=0.0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='dashboard.climatescenario')),
            ],
            options={
                'ordering': ('scenario', 'key', 'year'),
                'unique_together': {('scenario', 'year', 'key')},
            },
        ),
    ]
