# Generated by Django 6.0.5 on 2026-08-09 21:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_seed_climate_scenarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Actif', 'verbose_name_plural': 'Actifs'},
        ),
        migrations.AlterModelOptions(
            name='assetinventory',
            options={'verbose_name': "Inventaire d'actif", 'verbose_name_plural': "Inventaires d'actifs"},
        ),
        migrations.AlterModelOptions(
            name='carbon_emission',
            options={'verbose_name': 'Émission carbone', 'verbose_name_plural': 'Émissions carbone'},
        ),
        migrations.AlterModelOptions(
            name='characterizationfactor',
            options={'verbose_name': 'Facteur de caractérisation', 'verbose_name_plural': 'Facteurs de caractérisation'},
        ),
        migrations.AlterModelOptions(
            name='climatescenario',
            options={'ordering': ('order', 'key'), 'verbose_name': 'Scénario climatique', 'verbose_name_plural': 'Scénarios climatiques'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'Commodité', 'verbose_name_plural': 'Commodités'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='company_policy',
            options={'verbose_name': "Politique d'entreprise", 'verbose_name_plural': "Politiques d'entreprise"},
        ),
        migrations.AlterModelOptions(
            name='company_revenue',
            options={'verbose_name': "Chiffre d'affaires", 'verbose_name_plural': "Chiffres d'affaires"},
        ),
        migrations.AlterModelOptions(
            name='company_revenue_sector',
            options={'verbose_name': 'CA par sous-secteur', 'verbose_name_plural': 'CA par sous-secteur'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Devise', 'verbose_name_plural': 'Devises'},
        ),
        migrations.AlterModelOptions(
            name='disclosurerequirement',
            options={'verbose_name': 'Disclosure Requirement', 'verbose_name_plural': 'Disclosure Requirements'},
        ),
        migrations.AlterModelOptions(
            name='e4assessment',
            options={'verbose_name': 'Évaluation ESRS E4', 'verbose_name_plural': 'Évaluations ESRS E4'},
        ),
        migrations.AlterModelOptions(
            name='esg_data',
            options={'verbose_name': 'Donnée ESG', 'verbose_name_plural': 'Données ESG'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'verbose_name': 'Échange', 'verbose_name_plural': 'Échanges'},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': 'Flux', 'verbose_name_plural': 'Flux'},
        ),
        migrations.AlterModelOptions(
            name='impactcategory',
            options={'verbose_name': "Catégorie d'impact", 'verbose_name_plural': "Catégories d'impact"},
        ),
        migrations.AlterModelOptions(
            name='impactmethod',
            options={'verbose_name': 'Méthode de caractérisation', 'verbose_name_plural': 'Méthodes de caractérisation'},
        ),
        migrations.AlterModelOptions(
            name='ownership',
            options={'verbose_name': 'Détention', 'verbose_name_plural': 'Détentions'},
        ),
        migrations.AlterModelOptions(
            name='policy_level',
            options={'verbose_name': 'Niveau de politique', 'verbose_name_plural': 'Niveaux de politique'},
        ),
        migrations.AlterModelOptions(
            name='policy_subcategory',
            options={'verbose_name': 'Sous-catégorie de politique', 'verbose_name_plural': 'Sous-catégories de politique'},
        ),
        migrations.AlterModelOptions(
            name='policy_type',
            options={'verbose_name': 'Type de politique', 'verbose_name_plural': 'Types de politique'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'Production', 'verbose_name_plural': 'Productions'},
        ),
        migrations.AlterModelOptions(
            name='scenariovariable',
            options={'ordering': ('scenario', 'key', 'year'), 'verbose_name': 'Variable de scénario', 'verbose_name_plural': 'Variables de scénario'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Secteur', 'verbose_name_plural': 'Secteurs'},
        ),
        migrations.AlterModelOptions(
            name='sectorcreditprofile',
            options={'verbose_name': 'Profil crédit sectoriel', 'verbose_name_plural': 'Profils crédit sectoriels'},
        ),
        migrations.AlterModelOptions(
            name='subnationalregion',
            options={'verbose_name': 'Région infranationale', 'verbose_name_plural': 'Régions infranationales'},
        ),
        migrations.AlterModelOptions(
            name='subsector',
            options={'verbose_name': 'Sous-secteur', 'verbose_name_plural': 'Sous-secteurs'},
        ),
        migrations.AlterModelOptions(
            name='supplynode',
            options={'verbose_name': "Nœud d'approvisionnement", 'verbose_name_plural': "Nœuds d'approvisionnement"},
        ),
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='near_sensitive_zone',
            field=models.BooleanField(default=False, verbose_name="Proche d'une zone sensible"),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_carbon_sequestration',
            field=models.FloatField(default=0, verbose_name='Risque — séquestration carbone'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_coastal_inundation',
            field=models.FloatField(default=0, verbose_name='Aléa — submersion côtière'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_cyclone',
            field=models.FloatField(default=0, verbose_name='Aléa — cyclone'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_drought',
            field=models.FloatField(default=0, verbose_name='Aléa — sécheresse'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_flood',
            field=models.FloatField(default=0, verbose_name='Aléa — inondation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_heatwave',
            field=models.FloatField(default=0, verbose_name='Aléa — canicule'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_pest_control',
            field=models.FloatField(default=0, verbose_name='Risque — contrôle des ravageurs'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_pollination',
            field=models.FloatField(default=0, verbose_name='Risque — pollinisation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_precipitation_variation',
            field=models.FloatField(default=0, verbose_name='Aléa — variation des précipitations'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_soil_quality',
            field=models.FloatField(default=0, verbose_name='Risque — qualité des sols'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_temperature_variation',
            field=models.FloatField(default=0, verbose_name='Aléa — variation de température'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water',
            field=models.FloatField(default=0, verbose_name='Risque — approvisionnement en eau'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water_purification',
            field=models.FloatField(default=0, verbose_name="Risque — épuration de l'eau"),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water_stress',
            field=models.FloatField(default=0, verbose_name='Aléa — stress hydrique'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_wildfire',
            field=models.FloatField(default=0, verbose_name='Aléa — feu de forêt'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sensitive_zone_area_ha',
            field=models.FloatField(default=0, help_text='Renseigné seulement si « Proche d’une zone sensible » est coché.', verbose_name='Surface de la zone sensible (ha)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sensitive_zone_name',
            field=models.CharField(blank=True, help_text='Renseigné seulement si « Proche d’une zone sensible » est coché.', max_length=255, verbose_name='Nom de la zone sensible'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sensitive_zone_type',
            field=models.CharField(blank=True, choices=[('NATURA_2000', 'Natura 2000'), ('NATIONAL_PROTECTED', 'Aire protégée nationale'), ('UNESCO', 'Site UNESCO'), ('IUCN_KBA', 'IUCN Key Biodiversity Area'), ('OTHER', 'Autre')], help_text='Renseigné seulement si « Proche d’une zone sensible » est coché.', max_length=20, verbose_name='Type de zone sensible'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subnational_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subnationalregion', verbose_name='Région infranationale'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('Airport', 'Airport'), ('Mine', 'Mine'), ('Aluminium', 'Aluminium'), ('Factory', 'Factory'), ('Forest', 'Forest'), ('Office', 'Office'), ('Paper', 'Paper'), ('Refinery', 'Refinery'), ('Renewable', 'Renewable'), ('Smelter', 'Smelter')], default='Factory', max_length=255, verbose_name='Type de site'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='dashboard.asset', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.flow', verbose_name='Flux'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='value',
            field=models.FloatField(default=0.0, help_text='Valeur relevée sur le terrain, dans l’unité du flux sélectionné.', verbose_name='Valeur mesurée'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='year',
            field=models.IntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='carbon_emission',
            name='carbon_emission',
            field=models.FloatField(default=0, verbose_name='Émissions (tCO₂e)'),
        ),
        migrations.AlterField(
            model_name='carbon_emission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='carbon_emission',
            name='scope',
            field=models.CharField(max_length=255, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='carbon_emission',
            name='year',
            field=models.IntegerField(verbose_name='Exercice'),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='dashboard.impactcategory', verbose_name="Catégorie d'impact"),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfs', to='dashboard.commodity', verbose_name='Commodité'),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Laisser les deux vides pour un facteur global. La résolution suit l’ordre région → pays → global : le premier facteur trouvé gagne.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Laisser les deux vides pour un facteur global. La résolution suit l’ordre région → pays → global : le premier facteur trouvé gagne.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subnationalregion', verbose_name='Région infranationale'),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='characterizationfactor',
            name='value',
            field=models.FloatField(default=0.0, help_text='Impact généré par une unité de la commodité. Multiplié par la quantité produite pour obtenir l’impact total.', verbose_name='Facteur'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='family',
            field=models.CharField(choices=[('ORDERLY', 'Transition ordonnée'), ('DISORDERLY', 'Transition désordonnée'), ('TOO_LITTLE', 'Trop peu, trop tard'), ('HOT_HOUSE', 'Monde en surchauffe')], default='ORDERLY', max_length=20, verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clé technique'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='narrative',
            field=models.TextField(blank=True, verbose_name='Narratif'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Contrôle l’ordre d’affichage des scénarios dans les écrans.', verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='climatescenario',
            name='warming_c',
            field=models.FloatField(default=0.0, verbose_name='Réchauffement (°C)'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='biodiversity_loss_class',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Urbanisation', 'Urbanisation'), ('Mining', 'Mining')], default='Agriculture', help_text='Détermine lequel des trois taux de perte du pays s’applique : agriculture, urbanisation ou extraction minière.', verbose_name='Classe de perte de biodiversité'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='dependency_carbon_sequestration',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — séquestration carbone'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='dependency_pest_control',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — contrôle des ravageurs'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='dependency_pollination',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — pollinisation'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='dependency_soil_quality',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — qualité des sols'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='dependency_water',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — approvisionnement en eau'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='dependency_water_purification',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name="Dépendance — épuration de l'eau"),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='unit',
            field=models.CharField(default='tonnes', help_text='Unité dans laquelle les productions et les échanges de cette commodité sont exprimés (par défaut : tonnes).', max_length=255, verbose_name='Unité de mesure'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='isin',
            field=models.CharField(default='0', max_length=255, verbose_name='Code ISIN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(default='0', max_length=255, verbose_name='Ticker boursier'),
        ),
        migrations.AlterField(
            model_name='company_policy',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='company_policy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='company_policy',
            name='policy_date',
            field=models.DateField(default='2026-01-01', verbose_name="Date d'adoption"),
        ),
        migrations.AlterField(
            model_name='company_policy',
            name='policy_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy_level', verbose_name='Niveau de politique'),
        ),
        migrations.AlterField(
            model_name='company_revenue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='company_revenue',
            name='currency',
            field=models.CharField(max_length=255, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='company_revenue',
            name='revenue',
            field=models.FloatField(verbose_name="Chiffre d'affaires"),
        ),
        migrations.AlterField(
            model_name='company_revenue',
            name='year',
            field=models.IntegerField(verbose_name='Exercice'),
        ),
        migrations.AlterField(
            model_name='company_revenue_sector',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='company_revenue_sector',
            name='revenue',
            field=models.FloatField(verbose_name="Chiffre d'affaires"),
        ),
        migrations.AlterField(
            model_name='company_revenue_sector',
            name='subsector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subsector', verbose_name='Sous-secteur'),
        ),
        migrations.AlterField(
            model_name='company_revenue_sector',
            name='year',
            field=models.IntegerField(verbose_name='Exercice'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_agriculture',
            field=models.FloatField(default=0, verbose_name='Perte de biodiversité — agriculture'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_mining',
            field=models.FloatField(default=0, verbose_name='Perte de biodiversité — extraction minière'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_urbanization',
            field=models.FloatField(default=0, verbose_name='Perte de biodiversité — urbanisation'),
        ),
        migrations.AlterField(
            model_name='country',
            name='land_Governance',
            field=models.TextField(blank=True, verbose_name='Gouvernance foncière'),
        ),
        migrations.AlterField(
            model_name='country',
            name='land_ownership',
            field=models.CharField(max_length=255, verbose_name='Régime de propriété foncière'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='country',
            name='restoration_cost_m2',
            field=models.FloatField(default=0, verbose_name='Coût de restauration (par m²)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='water_Governance',
            field=models.TextField(blank=True, verbose_name="Gouvernance de l'eau"),
        ),
        migrations.AlterField(
            model_name='country',
            name='water_ownership',
            field=models.CharField(max_length=255, verbose_name="Régime de propriété de l'eau"),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, verbose_name='Code ISO'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ratio_USD',
            field=models.FloatField(default=1, verbose_name="Taux de conversion vers l'USD"),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=3, verbose_name='Symbole'),
        ),
        migrations.AlterField(
            model_name='disclosurerequirement',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_requirements', to='dashboard.e4assessment', verbose_name='Évaluation'),
        ),
        migrations.AlterField(
            model_name='disclosurerequirement',
            name='code',
            field=models.CharField(choices=[('E4_1', 'E4-1'), ('E4_2', 'E4-2'), ('E4_3', 'E4-3'), ('E4_4', 'E4-4'), ('E4_5', 'E4-5'), ('E4_6', 'E4-6')], help_text='Les DR applicables dépendent de la version du standard retenue sur l’évaluation (5 DR pour la version amendée 2025, 6 pour l’originale 2023).', max_length=10, verbose_name='Code du DR'),
        ),
        migrations.AlterField(
            model_name='disclosurerequirement',
            name='justification',
            field=models.TextField(blank=True, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='disclosurerequirement',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Non commencé'), ('NON_COMPLIANT', 'Non conforme'), ('PARTIAL', 'Partiel'), ('COMPLIANT', 'Conforme'), ('NOT_APPLICABLE', 'Non applicable')], default='NOT_STARTED', max_length=20, verbose_name='Statut de conformité'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e4_assessments', to='dashboard.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='leap_assess_notes',
            field=models.TextField(blank=True, verbose_name='LEAP — Assess, notes'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='leap_assess_status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Fait')], default='TODO', help_text='La phase Prepare est hors périmètre ESRS E4 : seules Locate, Evaluate et Assess servent à la détermination de matérialité.', max_length=20, verbose_name='LEAP — Assess, statut'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='leap_evaluate_notes',
            field=models.TextField(blank=True, verbose_name='LEAP — Evaluate, notes'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='leap_evaluate_status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Fait')], default='TODO', help_text='La phase Prepare est hors périmètre ESRS E4 : seules Locate, Evaluate et Assess servent à la détermination de matérialité.', max_length=20, verbose_name='LEAP — Evaluate, statut'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='leap_locate_notes',
            field=models.TextField(blank=True, verbose_name='LEAP — Locate, notes'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='leap_locate_status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Fait')], default='TODO', help_text='La phase Prepare est hors périmètre ESRS E4 : seules Locate, Evaluate et Assess servent à la détermination de matérialité.', max_length=20, verbose_name='LEAP — Locate, statut'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='materiality_justification',
            field=models.TextField(blank=True, verbose_name='Justification de matérialité'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='materiality_status',
            field=models.CharField(choices=[('NOT_ASSESSED', 'Non évaluée'), ('MATERIAL', 'Matérielle'), ('NOT_MATERIAL', 'Non matérielle')], default='NOT_ASSESSED', max_length=20, verbose_name='Statut de matérialité'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='reporting_year',
            field=models.IntegerField(default=2024, verbose_name='Exercice de reporting'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='standard_version',
            field=models.CharField(choices=[('AMENDED_2025', 'ESRS E4 amendé (déc. 2025) — 5 DR'), ('ORIGINAL_2023', 'ESRS E4 original (2023) — 6 DR')], default='AMENDED_2025', max_length=20, verbose_name='Version du standard'),
        ),
        migrations.AlterField(
            model_name='e4assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='esg_data',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='esg_data',
            name='employees_number',
            field=models.IntegerField(default=0, verbose_name='Nombre de salariés'),
        ),
        migrations.AlterField(
            model_name='esg_data',
            name='year',
            field=models.IntegerField(verbose_name='Exercice'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.commodity', verbose_name='Commodité'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='dashboard.supplynode', verbose_name='Consommateur'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='data_confidence',
            field=models.CharField(choices=[('asset', 'asset'), ('region', 'region'), ('country', 'country')], default='country', help_text='Précision de la localisation d’où provient cette donnée : relevée sur l’actif, estimée à la région, ou estimée au pays.', max_length=16, verbose_name='Résolution de la donnée'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='quantity',
            field=models.FloatField(verbose_name='Quantité échangée'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='dashboard.supplynode', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='tier',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position dans la chaîne : 0 opérations directes · 1 chaîne d’approvisionnement · 2 approvisionnement amont · 3 matières premières.', validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='year',
            field=models.IntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='key',
            field=models.CharField(help_text='Identifiant technique repris tel quel dans les clés JSON des vues. Ne pas modifier sur un enregistrement existant sans vérifier les vues qui le consomment.', max_length=50, unique=True, verbose_name='Clé technique'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='theme',
            field=models.CharField(blank=True, help_text='Clé d’appariement entre mesure et modèle : un inventaire d’actif est comparé aux catégories d’impact qui portent le même thème.', max_length=30, verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='key',
            field=models.CharField(help_text='Identifiant technique repris tel quel dans les clés JSON des vues. Ne pas modifier sur un enregistrement existant sans vérifier les vues qui le consomment.', max_length=100, unique=True, verbose_name='Clé technique'),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='level',
            field=models.CharField(choices=[('MIDPOINT', 'Midpoint'), ('ENDPOINT', 'Endpoint')], default='MIDPOINT', max_length=10, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dashboard.impactmethod', verbose_name='Méthode'),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='theme',
            field=models.CharField(blank=True, help_text='Clé d’appariement entre mesure et modèle : un inventaire d’actif est comparé aux catégories d’impact qui portent le même thème.', max_length=30, verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='impactmethod',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='impactmethod',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='impactmethod',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='Asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='ownership',
            field=models.CharField(max_length=255, verbose_name='Part de détention'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy_subcategory', verbose_name='Sous-catégorie'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_carbon_sequestration',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — séquestration carbone'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_coastal_inundation',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — submersion côtière'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_cyclone',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — cyclone'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_drought',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — sécheresse'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_flood',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — inondation'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_heatwave',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — canicule'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_pest_control',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — contrôle des ravageurs'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_pollination',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — pollinisation'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_precipitation_variation',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — variation des précipitations'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_soil_quality',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — qualité des sols'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_temperature_variation',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — variation de température'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_water',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — approvisionnement en eau'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_water_purification',
            field=models.FloatField(default=1.0, verbose_name="Vulnérabilité — épuration de l'eau"),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_water_stress',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — stress hydrique'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_wildfire',
            field=models.FloatField(default=1.0, verbose_name='Vulnérabilité — feu de forêt'),
        ),
        migrations.AlterField(
            model_name='policy_subcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='policy_subcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='policy_subcategory',
            name='policy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy_type', verbose_name='Type de politique'),
        ),
        migrations.AlterField(
            model_name='policy_type',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='policy_type',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='production',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='production',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.commodity', verbose_name='Commodité'),
        ),
        migrations.AlterField(
            model_name='production',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='production',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='production',
            name='estimated_revenue',
            field=models.FloatField(default=0.0, verbose_name='Revenu estimé'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production',
            field=models.FloatField(verbose_name='Quantité produite'),
        ),
        migrations.AlterField(
            model_name='production',
            name='subnational_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subnationalregion', verbose_name='Région infranationale'),
        ),
        migrations.AlterField(
            model_name='production',
            name='tier',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position dans la chaîne : 0 opérations directes · 1 chaîne d’approvisionnement · 2 approvisionnement amont · 3 matières premières.', validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='production',
            name='year',
            field=models.IntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='scenariovariable',
            name='key',
            field=models.CharField(choices=[('carbon_price', 'Prix du carbone (€/tCO₂e)'), ('hazard_multiplier', "Multiplicateur d'aléa")], max_length=30, verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='scenariovariable',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='dashboard.climatescenario', verbose_name='Scénario'),
        ),
        migrations.AlterField(
            model_name='scenariovariable',
            name='value',
            field=models.FloatField(default=0.0, help_text='L’unité dépend de la variable choisie : €/tCO₂e pour un prix du carbone, facteur sans unité pour un multiplicateur d’aléa.', verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='scenariovariable',
            name='year',
            field=models.IntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='NACE_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code NACE'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='carbon_pass_through',
            field=models.FloatField(default=0.3, verbose_name='Répercussion du coût carbone'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='ebitda_margin',
            field=models.FloatField(default=0.12, help_text='Valeur par défaut du secteur. L’utilisateur peut la surcharger dans l’écran de stress test climatique.', verbose_name="Marge d'EBITDA"),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='ebitda_volatility',
            field=models.FloatField(default=0.25, verbose_name="Volatilité de l'EBITDA"),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='pd_baseline',
            field=models.FloatField(default=0.015, help_text='Valeur par défaut du secteur. L’utilisateur peut la surcharger dans l’écran de stress test climatique.', verbose_name='Probabilité de défaut de référence'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to='dashboard.sector', verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='Mean_X',
            field=models.FloatField(default=0, verbose_name='Coordonnée X moyenne'),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='Mean_Y',
            field=models.FloatField(default=0, verbose_name='Coordonnée Y moyenne'),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='restoration_cost_m2',
            field=models.FloatField(default=0, verbose_name='Coût de restauration (par m²)'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='Carbon_Sequestration',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — séquestration carbone'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='NACE_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code NACE'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='Pest_control_dependency',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — contrôle des ravageurs'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='Pollination_dependency',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — pollinisation'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='Soil_quality_dependency',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — qualité des sols'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='Water_dependency',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name='Dépendance — approvisionnement en eau'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='Water_purification_dependency',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='Niveau de dépendance à ce service écosystémique. Converti en score de calcul : très faible 0 · faible 0,2 · moyen 0,5 · fort 0,7 · très fort 1.', max_length=2, verbose_name="Dépendance — épuration de l'eau"),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector', verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Un nœud requiert au moins un actif, une région ou un pays. Le plus précis des trois détermine sa résolution.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.asset', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.commodity', verbose_name='Commodité'),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Un nœud requiert au moins un actif, une région ou un pays. Le plus précis des trois détermine sa résolution.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Fournisseur externe'),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Un nœud requiert au moins un actif, une région ou un pays. Le plus précis des trois détermine sa résolution.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subnationalregion', verbose_name='Région infranationale'),
        ),
        migrations.AlterField(
            model_name='supplynode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
