# Generated by Django 6.0.5 on 2026-08-10 08:52
"""help_text « échelle non documentée » sur 40 champs numériques.

Migration sans effet en base : `help_text` fait partie de
`Field.non_db_attrs`, donc l'autodetecteur produit des AlterField que le
schema editor traduit en no-op. Verifie avec
`manage.py sqlmigrate dashboard 0045` : les 40 operations sortent en
`-- (no-op)`, aucune instruction SQL.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_libelles_metier_console'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='risk_carbon_sequestration',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Risque — séquestration carbone'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_coastal_inundation',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — submersion côtière'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_cyclone',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — cyclone'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_drought',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — sécheresse'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_flood',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — inondation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_heatwave',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — canicule'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_pest_control',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Risque — contrôle des ravageurs'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_pollination',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Risque — pollinisation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_precipitation_variation',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — variation des précipitations'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_soil_quality',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Risque — qualité des sols'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_temperature_variation',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — variation de température'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Risque — approvisionnement en eau'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water_purification',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name="Risque — épuration de l'eau"),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water_stress',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — stress hydrique'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_wildfire',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Aléa — feu de forêt'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_agriculture',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Perte de biodiversité — agriculture'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_mining',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Perte de biodiversité — extraction minière'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_urbanization',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Perte de biodiversité — urbanisation'),
        ),
        migrations.AlterField(
            model_name='country',
            name='restoration_cost_m2',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Coût de restauration (par m²)'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='score',
            field=models.FloatField(blank=True, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_carbon_sequestration',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — séquestration carbone'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_coastal_inundation',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — submersion côtière'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_cyclone',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — cyclone'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_drought',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — sécheresse'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_flood',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — inondation'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_heatwave',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — canicule'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_pest_control',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — contrôle des ravageurs'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_pollination',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — pollinisation'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_precipitation_variation',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — variation des précipitations'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_soil_quality',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — qualité des sols'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_temperature_variation',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — variation de température'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_water',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — approvisionnement en eau'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_water_purification',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name="Vulnérabilité — épuration de l'eau"),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_water_stress',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — stress hydrique'),
        ),
        migrations.AlterField(
            model_name='policy_level',
            name='vulnerability_wildfire',
            field=models.FloatField(default=1.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Vulnérabilité — feu de forêt'),
        ),
        migrations.AlterField(
            model_name='production',
            name='estimated_revenue',
            field=models.FloatField(default=0.0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Revenu estimé'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='carbon_pass_through',
            field=models.FloatField(default=0.3, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Répercussion du coût carbone'),
        ),
        migrations.AlterField(
            model_name='sectorcreditprofile',
            name='ebitda_volatility',
            field=models.FloatField(default=0.25, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name="Volatilité de l'EBITDA"),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='Mean_X',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Coordonnée X moyenne'),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='Mean_Y',
            field=models.FloatField(default=0, help_text='Échelle et unité non documentées à ce jour — vérifier le glossaire métier avant de saisir une valeur.', verbose_name='Coordonnée Y moyenne'),
        ),
    ]
