# Generated by Django 6.0.5 on 2026-08-10 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_help_text_echelle_non_documentee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company_revenue',
            name='ebitda',
            field=models.FloatField(default=0.0, verbose_name='EBITDA'),
        ),
        migrations.AddField(
            model_name='company_revenue',
            name='evic',
            field=models.FloatField(default=0.0, help_text="Enterprise Value Including Cash — dénominateur de l'impact financé.", verbose_name='EVIC'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fonds')),
                ('size', models.FloatField(default=0, verbose_name='Taille du fonds')),
                ('is_benchmark', models.BooleanField(default=False, verbose_name='Utiliser comme benchmark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('benchmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmarked_by', to='dashboard.portfolio', verbose_name='Benchmark')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.currency', verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Montant investi')),
                ('weight', models.FloatField(default=0, verbose_name='Poids (%)')),
                ('instrument_type', models.CharField(choices=[('EQUITY', 'Action (Equity)'), ('BOND', 'Obligation (Bond)')], default='EQUITY', max_length=10, verbose_name="Type d'instrument")),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='Maturité')),
                ('coupon_rate', models.FloatField(blank=True, null=True, verbose_name='Taux de coupon (%)')),
                ('face_value', models.FloatField(blank=True, null=True, verbose_name='Valeur nominale')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Entreprise')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='dashboard.portfolio', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Position de portefeuille',
                'verbose_name_plural': 'Positions de portefeuille',
                'unique_together': {('portfolio', 'company')},
            },
        ),
    ]
