# Generated by Django 6.0.5 on 2026-08-23 13:47

from django.db import migrations, models


def share_existing_benchmarks(apps, schema_editor):
    """Les benchmarks étaient visibles par tous : on préserve cette visibilité."""
    Portfolio = apps.get_model('dashboard', 'Portfolio')
    Portfolio.objects.filter(is_benchmark=True).update(is_shared=True)


def unshare_benchmarks(apps, schema_editor):
    """Rien à défaire : le champ is_shared disparaît avec la migration inverse."""


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_add_portfolio_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Visible en lecture par tous les utilisateurs. Réservé au staff.', verbose_name='Portefeuille commun'),
        ),
        migrations.RunPython(share_existing_benchmarks, unshare_benchmarks),
    ]
