# Generated by Django 6.0.5 on 2026-09-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_add_portfolio_is_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subnationalregion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subsector',
            name='description',
        ),
        migrations.AddField(
            model_name='country',
            name='restoration_cost_source',
            field=models.CharField(blank=True, choices=[('Country budget allocation', 'State'), ('Scientific studies', 'Scientific')], verbose_name='origine de la donnée du cout de restauration'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_carbon_sequestration',
            field=models.FloatField(default=0, help_text='A définir', verbose_name='Risque — séquestration carbone'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_coastal_inundation',
            field=models.FloatField(default=0, help_text='WRI coastal inondation score de 0 à 5', verbose_name='Aléa — submersion côtière'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_cyclone',
            field=models.FloatField(default=0, help_text='A définir', verbose_name='Aléa — cyclone'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_drought',
            field=models.FloatField(default=0, help_text='WRI drought score de 0 à 5', verbose_name='Aléa — sécheresse'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_flood',
            field=models.FloatField(default=0, help_text='WRI flood score de 0 à 5', verbose_name='Aléa — inondation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_heatwave',
            field=models.FloatField(default=0, help_text='A définir', verbose_name='Aléa — canicule'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_pest_control',
            field=models.FloatField(default=0, help_text='A définir', verbose_name='Risque — contrôle des ravageurs'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_pollination',
            field=models.FloatField(default=0, help_text='A définir', verbose_name='Risque — pollinisation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_precipitation_variation',
            field=models.FloatField(default=0, help_text='A définir', verbose_name='Aléa — variation des précipitations'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_soil_quality',
            field=models.FloatField(default=0, help_text='A définir, check WWF', verbose_name='Risque — qualité des sols'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_temperature_variation',
            field=models.FloatField(default=0, help_text='A définir', verbose_name='Aléa — variation de température'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water',
            field=models.FloatField(default=0, help_text='Risque eau du WRI de 0 a 5', verbose_name='Risque — approvisionnement en eau'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water_purification',
            field=models.FloatField(default=0, help_text='A définir', verbose_name="Risque — épuration de l'eau"),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_water_stress',
            field=models.FloatField(default=0, help_text='WRI water stress score de 0 a 5', verbose_name='Aléa — stress hydrique'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk_wildfire',
            field=models.FloatField(default=0, help_text='A définir', verbose_name='Aléa — feu de forêt'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='biodiversity_loss_class',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Urbanisation', 'Urbanisation'), ('Mining', 'Mining')], default='Agriculture', help_text='Détermine lequel des trois taux de perte du pays s’applique : agriculture, urbanisation ou extraction minière.', verbose_name='Classe de perte de biodiversité pour le calcul de dette biodiversité'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_agriculture',
            field=models.FloatField(default=0, help_text='En % par rapport à une unité de référence(i.e MSA agricole par rapport à état de référence)', verbose_name='Perte de biodiversité — agriculture'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_mining',
            field=models.FloatField(default=0, help_text='En % par rapport à une unité de référence(i.e zone minière par rapport à état de référence)', verbose_name='Perte de biodiversité — extraction minière'),
        ),
        migrations.AlterField(
            model_name='country',
            name='biodiversity_loss_urbanization',
            field=models.FloatField(default=0, help_text='En % par rapport à une unité de référence(i.e zone urbaine dense par rapport à état de référence)', verbose_name='Perte de biodiversité — urbanisation'),
        ),
        migrations.AlterField(
            model_name='country',
            name='land_ownership',
            field=models.CharField(max_length=255, verbose_name='Régime de propriété foncière à définir'),
        ),
        migrations.AlterField(
            model_name='country',
            name='restoration_cost_m2',
            field=models.FloatField(default=0, help_text='En € / m² issu des études locales ou des projets de développement du pays', verbose_name='Coût de restauration (par m²)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='water_ownership',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Privée'), ('Public Private partnership', 'Partenariat public privé')], max_length=255, verbose_name="Régime de propriété de l'eau"),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='Mean_X',
            field=models.FloatField(default=0, help_text='Coordonnée utilisé pour la projection en carte', verbose_name='Coordonnée X moyenne'),
        ),
        migrations.AlterField(
            model_name='subnationalregion',
            name='Mean_Y',
            field=models.FloatField(default=0, help_text='Coordonnée utilisé pour la projection en carte', verbose_name='Coordonnée Y moyenne'),
        ),
    ]
