# Generated by Django 6.0.5 on 2026-09-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_remove_sector_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='key',
            field=models.CharField(blank=True, help_text='Identifiant technique repris tel quel dans les clés JSON des vues. Ne pas modifier sur un enregistrement existant sans vérifier les vues qui le consomment.', max_length=50, null=True, unique=True, verbose_name='Clé technique'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='theme',
            field=models.CharField(blank=True, default='', help_text='Clé d’appariement entre mesure et modèle : un inventaire d’actif est comparé aux catégories d’impact qui portent le même thème.', max_length=30, verbose_name='Thème'),
        ),
    ]
