# Generated by Django 6.0.5 on 2026-09-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_flow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production',
        ),
    ]
