# Generated by Django 6.0.5 on 2026-09-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_delete_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplynode',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='supplynode',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='supplynode',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplynode',
            name='region',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='SupplyNode',
        ),
    ]
