# Generated by Django 6.0.5 on 2026-09-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_delete_supply_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carbon_emission',
        ),
    ]
